---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-backend
  labels:
    app: timber-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timber-backend
  template:
    metadata:
      labels:
        app: timber-backend
    spec:
      containers:
      - name: timber-backend
        image: ghcr.io/lalyos/timber-backend:v1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: timber-backend
  name: timber-backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: timber-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-frontend
  labels:
    app: timber-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timber-frontend
  template:
    metadata:
      labels:
        app: timber-frontend
    spec:
      containers:
      - name: timber-frontend
        image: eu.gcr.io/container-solutions-workshops/timber/frontend:v1.0
        ports:
        - containerPort: 8080
        env:
        - {name: TIMBER_BACKEND_API_URL, value: "http://timber-backend:8080"}
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: timber-frontend
  name: timber-frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: timber-frontend
  type: NodePort
