apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-demo
  labels:
    app: stress-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress-demo
  template:
    metadata:
      labels:
        app: stress-demo
    spec:
      containers:
        - name: stress
          image: progrium/stress:latest
          command: ["/usr/bin/stress"]
          args: ["--cpu", "5", "--timeout", "600s"]
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"