---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-backend
  labels:
    app: timber-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timber-backend
  template:
    metadata:
      labels:
        app: timber-backend
    spec:
      containers:
      - name: timber-backend
        image: eu.gcr.io/container-solutions-workshops/timber/backend
        ports:
        - containerPort: 8080
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName